#!/usr/bin/env bash

set -o errexit

function usage() {
    local SCRIPT=$(basename "$0")
    echo "Usage: $SCRIPT <command> <params>"
    echo
    echo "Commands:"
    echo -e "\tcreate <db_name>"
    echo -e "\tdump <db_name>"
    echo -e "\tdrop <db_name>"
    echo -e "\trestore <db_name> <dump_file>"
    exit
}

function dump() {
    local DB_NAME=$1
    local DATE=$(date "+%Y-%m-%d")
    local OUTPUT="${DB_NAME}.${DATE}.sql.dump"
    pg_dump $DB_NAME > $OUTPUT
    tar -czf "${OUTPUT}.tar.gz" $OUTPUT
}

function drop() {
    local DB_NAME=$1
    psql -d postgres -c "DROP DATABASE IF EXISTS \"$DB_NAME\""
}

function create() {
    local DB_NAME=$1
    psql -d postgres -c "CREATE DATABASE \"$DB_NAME\""
}

function restore() {
    local DB_NAME=$1
    local DUMP=$2

    local FOO="${DUMP%.*}"
    FOO="${FOO%.*}"

    local EXT="${DUMP##*.}"
    if [ "gz" == "$EXT" ]; then
        DUMP="$FOO"
    fi

    psql "${DB_NAME}" < "${DUMP}"
}

#-- main -----------------------------------------------------------------------

if [[ -z "$1" ]]; then
    usage
fi
CMD=$1; shift

case $CMD in
    create)
        create $@
        ;;
    dump)
        dump $@
        ;;
    drop)
        drop $@
        ;;
    restore)
        restore $@
        ;;
    *)
        usage
        ;;
esac
