#!/usr/bin/env awk -f

substr($2,0,4) == "prod" {
    if($3 != "UP") { down[$2] = $3 }
}

END {
    for (i in down) { len += 1 }
    
    if (len > 0) {
	for (i in down) {
	    printf "%s is %s\n", i, down[i]
	}
    } else {
	print "OK"
    }
}
