#!/usr/bin/env bash

function pia_vpn() {
    local ON=`systemctl status pia | grep Active | awk '{print $2}' | grep active`
    echo $ON
}

function mogo_vpn() {
    local ON=`nmcli con show "Mogo VPN (PPTP)" | grep "VPN-STATE"`
    echo $ON
}

function mem_free() {
    free -m | awk 'FNR == 2 { printf "%.0f%s", ($4/$2)*100, "%" }'
}

function i3wrapper() {
    i3status | while :
    do
        read line
	echo "mem $(mem_free) | $line" || exit 1
    done
}

i3wrapper
