#!/usr/bin/env sh

function usage() {
    echo "Usage: network-admin subcommand [start|stop]"
    echo
    echo "subcommands:"
    echo "- restart"
    echo "- mogo start|stop"
    echo "- dnscrypt start|stop"
    echo "- wifi mogo|home start"
    echo "- vpn pia|mogo start|stop|status"
    echo "- default start|stop"
    echo "- help"
    echo "- status"
    echo
    echo "NOTE: \`default' doesn't accept \`start' or \`stop'"
    echo "Mogo VPN info is at /etc/NetworkManager/system-connections/Mogo VPN (PPTP)"
}

case "$1" in
    # Completely restart all networking for the system.
    #---------------------------------------------------------------------------
    restart)
        sudo systemctl stop systemd-resolved
        sudo systemctl stop systemd-networkd
        sudo systemctl stop NetworkManager
        sudo systemctl start systemd-resolved
        sudo systemctl start systemd-networkd
        sudo systemctl start NetworkManager
        ;;

    # Start Mogo VPN and other work:
    #-----------------------------------------------------------------------
    mogo)
        case "$2" in
            start)
                sudo systemctl stop pia
                sudo systemctl stop dnscrypt-proxy.socket
                sudo systemctl stop dnscrypt-proxy.service
                sudo systemctl stop dnsmasq.service
                sudo chattr -i /etc/resolv.conf
                sudo chmod o+w /etc/resolv.conf
                sudo echo "domain MOGO.LAN" > /etc/resolv.conf
                sudo echo "nameserver 10.32.102.10" >> /etc/resolv.conf
                sudo echo "nameserver 10.32.104.10" >> /etc/resolv.conf
                sudo chmod o-w /etc/resolv.conf
                sudo chattr +i /etc/resolv.conf
                ;;
            stop)
                network-admin default start
                ;;
            *)
                usage
                ;;
        esac
        ;;

    # Start DNS Encryption:
    #-----------------------------------------------------------------------
    dnscrypt)
        case "$2" in
            start)
                sudo systemctl stop pia
                sudo systemctl stop dnscrypt-proxy.socket
                sudo systemctl stop dnscrypt-proxy.service
                sudo systemctl stop dnsmasq.service
                sudo chattr -i /etc/resolv.conf
                sudo chmod o+w /etc/resolv.conf
                sudo echo "nameserver 127.0.0.1" > /etc/resolv.conf
                sudo chmod o-w /etc/resolv.conf
                sudo chattr +i /etc/resolv.conf
                sudo systemctl start dnscrypt-proxy.socket
                sudo systemctl start dnscrypt-proxy.service
                sudo systemctl start dnsmasq.service
                ;;
            stop)
                network-admin default start
                ;;
            *)
                usage
                ;;
        esac
        ;;

    wifi)
        case "$2" in
            mogo)
                case "$3" in
                    start)
                        sudo wpa_supplicant -i wlp3s0 -D wext -c /etc/wpa_supplicant/mogonet.conf
                        #sudo dhcpcd wlp3s0
                    ;;
                esac
            ;;
            home)
                case "$3" in
                    start)
                        sudo wpa_supplicant -B -i wlp3s0 -D wext -c /etc/wpa_supplicant/whispering-rock.conf
                        sudo dhcpcd wlp3s0
                    ;;
                esac
            ;;
            *)
            ;;
        esac
        ;;

    # Start and Stop PIA personal VPN
    #-----------------------------------------------------------------------
    vpn)
        case "$2" in
            pia)
                case "$3" in
                    start)
                        sudo systemctl start pia
                        ;;
                    stop)
                        sudo systemctl stop pia
                        ;;
                    status)
                        systemctl status pia | grep Active
                        ;;
                    *)
                        echo "Unknown command. Try -h"
                        ;;
                esac
                ;;
            mogo)
                case "$3" in
                    start)
                        sudo nmcli con up id "Mogo VPN (PPTP)"
                        ;;
                    stop)
                        sudo nmcli con down id "Mogo VPN (PPTP)"
                        ;;
                    status)
                        sudo nmcli con show "Mogo VPN (PPTP)" | grep 'VPN-STATE'
                        ;;
                    *)
                        echo "Unknown command. Try -h"
                        ;;
                esac
                ;;
            *)
                usage
                ;;
        esac
        ;;

    # Default DNS configuration in case there are problems.
    #-----------------------------------------------------------------------
    default)
        case "$2" in
            start)
                sudo systemctl stop pia
                sudo systemctl stop dnscrypt-proxy.socket
                sudo systemctl stop dnscrypt-proxy.service
                sudo systemctl stop dnsmasq.service
                sudo chattr -i /etc/resolv.conf
                sudo chmod o+w /etc/resolv.conf
                # OpenDNS Family Shield defaults
                sudo echo "nameserver 208.67.222.222" > /etc/resolv.conf
                sudo echo "nameserver 208.67.220.220" >> /etc/resolv.conf
                sudo chmod o-w /etc/resolv.conf
                sudo chattr +i /etc/resolv.conf
                ;;
            stop)
                sudo systemctl stop pia
                ;;
            *)
                usage
                ;;
        esac
        ;;

    # Show status of pia and dnscrypt-proxy services.
    #-----------------------------------------------------------------------
    status)
        echo "pia status "
        echo "--------------------------------------------------------------------------------"
        curl -s https://www.privateinternetaccess.com | grep -P 'You are (not )?protected'
        echo
        sudo systemctl status pia | cat | grep Active
        echo
        echo "dnscrypt-proxy status "
        echo "--------------------------------------------------------------------------------"
        sudo systemctl status dnscrypt-proxy | cat | grep Active
        echo
        echo "dnsmasq status "
        echo "--------------------------------------------------------------------------------"
        sudo systemctl status dnsmasq | cat | grep Active
        echo
        echo "/etc/resolv.conf"
        echo "--------------------------------------------------------------------------------"
        cat /etc/resolv.conf

        # Get dnscrypt-proxy IP address:
        # systemctl status dnscrypt-proxy | cat | sed -rn 's|.*Proxying from 127.0.0.1:53 to (.+)|\1|p'
        # Then use wireshark cli (tshark) to inspect traffic to this ip.
        #   (Not sure how to do this properly yet.)
        #   tshark dst net 77.66.84.233 doesn't capture anything.
        ;;

    *)
        usage
        ;;
esac
